# Generated by Django 3.1.2 on 2020-12-07 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_to_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvstore',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
