# Generated by Django 3.1 on 2020-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Insert Interesting Title Here', max_length=255, verbose_name='Title')),
                ('data', models.TextField(help_text='Insert Content Here.', verbose_name='Reminders')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('dead_line', models.DateTimeField(help_text='The time by which this task has to be completed', verbose_name='Deadline')),
                ('is_done', models.BooleanField(help_text="Mark 'Done' if this task is done.")),
            ],
        ),
    ]
