# Generated by Django 3.1 on 2020-09-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20200906_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data',
            field=models.CharField(max_length=255, verbose_name='Reminders'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dead_line',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
